{{- /*
  Strimzi Cluster Operator (Helm-templated, no CRDs)
*/ -}}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-cluster-operator
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator-role
rules:
  # Access to core Kubernetes resources
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
      - endpoints
      - events
    verbs: ["*"]

  # Apps resources
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs: ["*"]

  # RBAC for per-resource access Strimzi dynamically creates
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs: ["*"]

  # Strimzi CRDs (operator manages these)
  - apiGroups: ["kafka.strimzi.io"]
    resources: ["*"]
    verbs: ["*"]

  # API extensions access (CRDs already installed, but operator still reads them)
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-cluster-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-cluster-operator-role
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: {{ .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: {{ .Values.strimzi.image }}
          imagePullPolicy: IfNotPresent
          env:
            # WATCHED NAMESPACES MUST BE A COMMA-LIST, NOT "*"
            - name: STRIMZI_NAMESPACE
              value: "{{ .Values.strimzi.watchedNamespaces }}"

            # Optional but recommended
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_LOG_LEVEL
              value: "{{ .Values.strimzi.logLevel }}"

          ports:
            - name: health
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
